### PR TITLE
Add support for not null terminated string

### PR DESCRIPTION
**Pull request by aki017**

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Thanks for your patch! LGTM.

**Comment by Asmod4n** [comment]
@matsumoto-r @aki017 this is leaking memory, mallocs like here https://github.com/matsumoto-r/mruby-redis/blob/master/src/mrb_redis.c#L127 are not needed
.
```c
return mrb_str_new(mrb, r->str, r->len);
```

should be enough.

**Comment by matsumoto-r** [comment]
@Asmod4n Thank you for your notice. I also think this malloc is leaking memory, but `r->str` was freed after `freeReplyObject(r)`. Do you have any idea?

**Comment by Asmod4n** [comment]
@matsumoto-r ```mrb_str_new``` copies the contents to a new buffer, might you be mistaking it for ```mrb_str_new_static``` which only points to the pointer of a string?

**Comment by matsumoto-r** [comment]
@Asmod4n oh... got something wrong. Thank you for your points!

**Pull request merged**
